name: "ci"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CACHE_VERSION: v1

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0"
          elixir-version: "1.12"

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Restore cached deps
        uses: actions/cache@v1
        with:
          path: deps
          key: deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            deps-${{ env.CACHE_VERSION }}-

      - name: Restore cached build
        uses: actions/cache@v1
        with:
          path: _build
          key: build-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            build-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            build-${{ env.CACHE_VERSION }}-

      - run: mix deps.get
      - run: mix ci.check
